image:
  repository: mcr.microsoft.com/azure-cli
  tag: latest
  pullPolicy: IfNotPresent

replicaNum: 1

namespace: default

# Helm values configurations for CSI Driver
csi:
  pvName: azurefile-csi-pv
  pvcName: azurefile-csi-pvc
  secretName: azure-secret
  storageClassName: azurefile-csi
  mountPath: "/mnt/azure"
  azureResourceGroupName:
  azureStorageAccountName:
  azureStorageAccountKey:
  azureFileShareName: 
