apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "az-cli.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaNum }}
  selector:
    matchLabels:
      {{- include "az-cli.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        {{- include "az-cli.labels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - sh
        - -c
        - "sleep 10000"
        volumeMounts:
        - name: example-azure-csi-volume
          mountPath: {{ .Values.csi.mountPath }}
          readOnly: true
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumes:
        - name: example-azure-csi-volume
          persistentVolumeClaim:
            claimName: {{ .Values.csi.pvcName }}
