apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.csi.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: "1Gi"